<?xml version="1.0"?>
<!-- Copyright (c) 2016 The UUV Simulator Authors.
     All rights reserved.
     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- includes -->
  <xacro:include filename="$(find uuv_descriptions)/urdf/common.urdf.xacro" />
  <xacro:include filename="$(find uuv_dave)/urdf/sensor_snippets.xacro"/>
  <xacro:include filename="$(find uuv_gazebo_ros_plugins)/urdf/snippets.xacro"/>  

  <!-- Properties for the OASYS glider, see Table 1 in the report in Overleaf -->
  <xacro:property name="mass" value="4.605" />
 <xacro:property name="moving_mass" value="1.145" />
  <xacro:property name="length" value="1.450" />
  <xacro:property name="diameter" value="0.0775" />
  <xacro:property name="radius" value="${diameter*0.5}" />
  <xacro:property name="volume" value="0.005" />
  <xacro:property name="cog" value="0.003 0 -0.015" />
  <xacro:property name="cob" value="0 0 0"/>
  <xacro:property name="rho" value="1027.0" />

  <xacro:property name="area" value="0.004155" />
  <xacro:property name="length" value="1.450" />

  <xacro:property name="namespace" value="glider_OASYS"/>
  <xacro:property name="visual_mesh_file" value="file://$(find uuv_dave)/models/glider_slocum/mesh/AssemblyExternal.dae" />
  <xacro:property name="collision_mesh_file" value="file://$(find uuv_dave)/models/glider_slocum/mesh/AssemblyExternal.dae" />
 <xacro:property name="moving_mass_mesh_file" value="file://$(find uuv_dave)/models/glider_slocum/mesh/Moving_mass.dae" />
 
<!-- Include baselink -->   
  <xacro:macro name="glider_OASYS" params="namespace debug inertial_reference_frame">
    <link name="${namespace}/base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="${visual_mesh_file}" scale="1 1 1" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="${collision_mesh_file}" scale="1 1 1" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${mass}"/>
        <origin xyz="${cog}" rpy="0 0 0" />
        <inertia ixx="0.832878872" ixy="-0.000488959" ixz="-0.000002733" iyy="0.007467393" iyz="0.000050498" izz="0.829675627" /> 
	 <!-- <inertia ixx="0.831878872" ixy="-0.000488959" ixz="-0.000002733" iyy="0.006427393" iyz="0.000050498" izz="0.829475627" /> -->
      </inertial>
    </link>


   <!-- Set up moving mass link 

 <link name="${namespace}/moving_mass_link">
      <visual>
        <origin xyz="0.05 -0.007 -0.01" rpy="0 0 -0.785" />
        <geometry>
          <mesh filename="${moving_mass_mesh_file}" scale="1 1 1" />
        </geometry>
      </visual>
	<collision>
        <origin xyz="0.05 -0.007 -0.01" rpy="0 0 -0.785" />
        <geometry>
          <mesh filename="${moving_mass_mesh_file}" scale="1 1 1" />
        </geometry>
      </collision>
	<inertial>
        <mass value="${moving_mass}" />
        <origin xyz="0.05 -0.007 -0.02" rpy="0 0 -0.785" />
        <inertia ixx="0.001270" ixy="0.00004" ixz="0.00004" iyy=" 0.001241" iyz="0" izz="0.000232" />
      </inertial>
    </link>
    <joint name="${namespace}/moving_mass_joint" type="prismatic">
      <origin xyz="0.05 -0.007 -0.02" rpy="0 0 -0.785" />
      <parent link="${namespace}/base_link"/>
      <child link="${namespace}/moving_mass_link"/>
      <axis xyz="1 0 0" />
      <limit effort="0.0001" velocity="0.00001" upper="0.1" lower="-0.1" />
    </joint> -->



 <!-- revolute joint for rolling mass
  <joint name="${namespace}/moving_mass_joint" type="revolute">
      <origin xyz="-0.2 -0.02 0" rpy="0 0 0" />
      <parent link="${namespace}/base_link"/>
      <child link="${namespace}/moving_mass_link"/>
      <axis xyz="1 0 0" />
      <limit effort="0.0001" velocity="0.0001" upper="1.57" lower="-1.57" />
    </joint> -->

    
  
    <!-- Set up hydrodynamic plugin -->
      <gazebo>
      <plugin name="${namespace}_uuv_plugin" filename="libuuv_underwater_object_ros_plugin.so">
        <fluid_density>${rho}</fluid_density>
        <flow_velocity_topic>hydrodynamics/current_velocity</flow_velocity_topic>
        <debug>${debug}</debug>
        <link name="${namespace}/base_link">
          <volume>${volume}</volume>
          <center_of_buoyancy>${cob}</center_of_buoyancy>
	<neutrally_buoyant>0</neutrally_buoyant> 
          <hydrodynamic_model>
            <type>fossen</type>
	       
               <added_mass>
            0.7     0     0     0     0     0
            0     2.5    0     0     0     0
            0     0     2.5    0     0     0
            0     0     0     0.005 0     0
            0     0     0     0     0.5   0
            0     0     0     0     0     0.5
          </added_mass>
       
          <linear_damping>
            -0.7  0     0     0     0     0
            0     -7   0     0     0     1.5
            0     0     -7   0     -1.5 0
            0     0     0     -0.3  0     0
            0     0     1   0     -3.7  0
            0     -1  0     0     0     -3.7
          </linear_damping>
          </hydrodynamic_model>
        </link>
      </plugin>   
    </gazebo>


    <!-- Include the battery modules -->    
    <xacro:basic_linear_battery_macro
      namespace="${namespace}"
      parent_link="${namespace}/base_link"
      prefix=""
      open_circuit_voltage_constant_coef="3.7"
      open_circuit_voltage_linear_coef="-3.1424"
      initial_charge="1.1665"
      capacity="0.5"
      resistance="0.002"
      smooth_current_tau="1.9499"
      voltage="4.2"
      update_rate="2.0"/>

    <!-- Include sensor modules -->
    <xacro:include filename="$(find uuv_dave)/urdf/glider_OASYS_sensors.xacro"/>
  </xacro:macro>
 

</robot>
