// Generated by gencpp from file usbl_gazebo/USBLResponse.msg
// DO NOT EDIT!


#ifndef USBL_GAZEBO_MESSAGE_USBLRESPONSE_H
#define USBL_GAZEBO_MESSAGE_USBLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace usbl_gazebo
{
template <class ContainerAllocator>
struct USBLResponse_
{
  typedef USBLResponse_<ContainerAllocator> Type;

  USBLResponse_()
    : transceverID(0)
    , responseID(0)
    , data()  {
    }
  USBLResponse_(const ContainerAllocator& _alloc)
    : transceverID(0)
    , responseID(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _transceverID_type;
  _transceverID_type transceverID;

   typedef int32_t _responseID_type;
  _responseID_type responseID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::usbl_gazebo::USBLResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usbl_gazebo::USBLResponse_<ContainerAllocator> const> ConstPtr;

}; // struct USBLResponse_

typedef ::usbl_gazebo::USBLResponse_<std::allocator<void> > USBLResponse;

typedef boost::shared_ptr< ::usbl_gazebo::USBLResponse > USBLResponsePtr;
typedef boost::shared_ptr< ::usbl_gazebo::USBLResponse const> USBLResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usbl_gazebo::USBLResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usbl_gazebo::USBLResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::usbl_gazebo::USBLResponse_<ContainerAllocator1> & lhs, const ::usbl_gazebo::USBLResponse_<ContainerAllocator2> & rhs)
{
  return lhs.transceverID == rhs.transceverID &&
    lhs.responseID == rhs.responseID &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::usbl_gazebo::USBLResponse_<ContainerAllocator1> & lhs, const ::usbl_gazebo::USBLResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace usbl_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::usbl_gazebo::USBLResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usbl_gazebo::USBLResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usbl_gazebo::USBLResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usbl_gazebo::USBLResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usbl_gazebo::USBLResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usbl_gazebo::USBLResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usbl_gazebo::USBLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7457a516da54e3edd1c04a2bda0888f2";
  }

  static const char* value(const ::usbl_gazebo::USBLResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7457a516da54e3edULL;
  static const uint64_t static_value2 = 0xd1c04a2bda0888f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::usbl_gazebo::USBLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usbl_gazebo/USBLResponse";
  }

  static const char* value(const ::usbl_gazebo::USBLResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usbl_gazebo::USBLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 transceverID\n"
"int32 responseID\n"
"string data\n"
;
  }

  static const char* value(const ::usbl_gazebo::USBLResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usbl_gazebo::USBLResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.transceverID);
      stream.next(m.responseID);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct USBLResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usbl_gazebo::USBLResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usbl_gazebo::USBLResponse_<ContainerAllocator>& v)
  {
    s << indent << "transceverID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.transceverID);
    s << indent << "responseID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.responseID);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USBL_GAZEBO_MESSAGE_USBLRESPONSE_H
